#!/bin/bash
# ═══════════════════════════════════════════════════════════════
# ProveRank — Logo Fix for Landing + Auth Pages
# Replaces old PRLogo function in ALL public pages
# ═══════════════════════════════════════════════════════════════

G='\033[0;32m'; R='\033[0;31m'; Y='\033[1;33m'; B='\033[1;34m'; N='\033[0m'

# Auto-detect project root
if [ -f "./frontend/package.json" ]; then
  FE="./frontend"
elif [ -f "../frontend/package.json" ]; then
  FE="../frontend"
elif [ -f "~/workspace/frontend/package.json" ]; then
  FE="~/workspace/frontend"
else
  FE=$(find . ~/workspace -name "package.json" -path "*/frontend/*" 2>/dev/null | head -1 | xargs dirname 2>/dev/null)
fi

echo -e "${B}📁 Frontend path: $FE${N}"

# ── NEW PRLogo component (Split Block Monogram T1) ──
NEW_LOGO='function PRLogo({size=36}:{size?:number}) {
  const blockSize = size * 0.94
  const pSize = Math.round(blockSize * 0.63)
  const rSize = Math.round(blockSize * 0.63)
  const fontSize = Math.round(pSize * 0.52)
  const radius = Math.round(pSize * 0.28)
  return (
    <div style={{position:"relative",width:blockSize,height:blockSize,flexShrink:0,display:"inline-flex"}}>
      <div style={{
        position:"absolute",top:0,left:0,
        width:pSize,height:pSize,
        borderRadius:radius,
        background:"linear-gradient(135deg,#4D9FFF,#00D4FF)",
        display:"flex",alignItems:"center",justifyContent:"center",
        fontSize:fontSize,fontWeight:900,fontFamily:"Inter,sans-serif",
        color:"#030810",
        boxShadow:"0 4px 16px rgba(77,159,255,0.4)"
      }}>P</div>
      <div style={{
        position:"absolute",bottom:0,right:0,
        width:rSize,height:rSize,
        borderRadius:radius,
        background:"rgba(0,212,255,0.1)",
        border:"1.5px solid rgba(0,212,255,0.45)",
        display:"flex",alignItems:"center",justifyContent:"center",
        fontSize:fontSize,fontWeight:900,fontFamily:"Inter,sans-serif",
        color:"#00D4FF",
        backdropFilter:"blur(8px)"
      }}>R</div>
    </div>
  )
}'

# Pages to fix — these exist in repo but not generated by scripts
PAGES=(
  "$FE/app/page.tsx"
  "$FE/app/login/page.tsx"
  "$FE/app/register/page.tsx"
  "$FE/app/forgot-password/page.tsx"
  "$FE/app/components/PRLogo.tsx"
  "$FE/components/PRLogo.tsx"
  "$FE/app/components/Logo.tsx"
  "$FE/components/Logo.tsx"
)

python3 - << PYEOF
import os, re

new_logo = '''function PRLogo({size=36}:{size?:number}) {
  const blockSize = size * 0.94
  const pSize = Math.round(blockSize * 0.63)
  const rSize = Math.round(blockSize * 0.63)
  const fontSize = Math.round(pSize * 0.52)
  const radius = Math.round(pSize * 0.28)
  return (
    <div style={{position:"relative",width:blockSize,height:blockSize,flexShrink:0,display:"inline-flex"}}>
      <div style={{
        position:"absolute",top:0,left:0,
        width:pSize,height:pSize,
        borderRadius:radius,
        background:"linear-gradient(135deg,#4D9FFF,#00D4FF)",
        display:"flex",alignItems:"center",justifyContent:"center",
        fontSize:fontSize,fontWeight:900,fontFamily:"Inter,sans-serif",
        color:"#030810",
        boxShadow:"0 4px 16px rgba(77,159,255,0.4)"
      }}>P</div>
      <div style={{
        position:"absolute",bottom:0,right:0,
        width:rSize,height:rSize,
        borderRadius:radius,
        background:"rgba(0,212,255,0.1)",
        border:"1.5px solid rgba(0,212,255,0.45)",
        display:"flex",alignItems:"center",justifyContent:"center",
        fontSize:fontSize,fontWeight:900,fontFamily:"Inter,sans-serif",
        color:"#00D4FF",
        backdropFilter:"blur(8px)"
      }}>R</div>
    </div>
  )
}'''

fe = os.environ.get('FE_PATH', './frontend')

# Find ALL tsx/ts files that contain PRLogo function definition
search_dirs = [fe, './frontend', '../frontend', os.path.expanduser('~/workspace/frontend')]

all_files = []
for d in search_dirs:
    if os.path.exists(d):
        for root, dirs, files in os.walk(d):
            # Skip node_modules
            dirs[:] = [x for x in dirs if x != 'node_modules' and x != '.next']
            for f in files:
                if f.endswith(('.tsx', '.ts')):
                    all_files.append(os.path.join(root, f))
        break

print(f"Scanning {len(all_files)} files...")

fixed = []
for filepath in all_files:
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()
        
        if 'PRLogo' not in content:
            continue
            
        original = content
        
        # Pattern: match old hexagon SVG based PRLogo function
        # Match: function PRLogo(...) { ... svg ... polygon ... } 
        pattern = r'(export\s+)?function PRLogo\(\{size[^}]*\}[^)]*\)\s*\{[^}]+(?:svg|polygon|hexagon|feGaussianBlur)[^}]*(?:\}[^}]*){1,10}\}'
        
        if re.search(pattern, content, re.DOTALL):
            # Replace with new logo
            def replacer(m):
                prefix = 'export ' if m.group(1) else ''
                return prefix + new_logo
            content = re.sub(pattern, replacer, content, flags=re.DOTALL)
            
        # Also simple exact match for known patterns
        old_patterns = [
            # Pattern from admin script
            '''function PRLogo({size=36}:{size?:number}) {
  const r=size/2''',
            # Pattern from student script  
            '''export function PRLogo({size=40}:{size?:number}) {
  const r=size/2''',
        ]
        
        for op in old_patterns:
            if op in content:
                # Find end of this function
                start = content.find(op)
                # Find closing } at function level
                depth = 0
                i = start
                func_end = start
                in_func = False
                while i < len(content):
                    if content[i] == '{':
                        depth += 1
                        in_func = True
                    elif content[i] == '}':
                        depth -= 1
                        if in_func and depth == 0:
                            func_end = i + 1
                            break
                    i += 1
                
                old_func = content[start:func_end]
                is_export = start > 0 and content[max(0,start-8):start].strip().endswith('export')
                replacement = ('export ' if is_export else '') + new_logo
                
                if is_export:
                    content = content[:max(0,content.rfind('export', 0, start))] + replacement + content[func_end:]
                else:
                    content = content[:start] + replacement + content[func_end:]
                print(f"  ✅ Fixed (exact match): {filepath}")
        
        if content != original:
            with open(filepath, 'w', encoding='utf-8') as f:
                f.write(content)
            fixed.append(filepath)
            print(f"  💾 Saved: {os.path.basename(filepath)}")
            
    except Exception as e:
        print(f"  ⚠️  Skip {filepath}: {e}")

print(f"\n{'='*50}")
print(f"✅ Fixed {len(fixed)} files:")
for f in fixed:
    print(f"   - {f}")

if not fixed:
    print("⚠️  No files auto-fixed.")
    print("   The logo may be in a shared component file.")
    print("   Check: app/components/ or components/ folder")

PYEOF

echo ""
echo -e "${G}🚀 Now run:${N}"
echo "   git add ."
echo "   git commit -m 'Fix logo on landing + auth pages'"
echo "   git push origin main"
