const fs = require('fs');
const FILE = 'frontend/app/admin/x7k2p/page.tsx';
let t = fs.readFileSync(FILE, 'utf8');

// ── 1. ADD STATES ──────────────────────────────────────────
const s1o = "  const [qPreview,setQPreview]=useState(false)";
const s1n = [
  "  const [qPreview,setQPreview]=useState(false)",
  "  const [qBV,setQBV]=useState('home')",
  "  const [qSec,setQSec]=useState('all')",
  "  const [qBioSub,setQBioSub]=useState('all')",
  "  const [bulkSel,setBulkSel]=useState([])",
  "  const [selQId,setSelQId]=useState(null)",
  "  const [editQD,setEditQD]=useState(null)",
  "  const [savingEQ,setSavingEQ]=useState(false)",
  "  const [stdPrv,setStdPrv]=useState(false)",
  "  const [aiGO,setAiGO]=useState(false)",
  "  const [aiGStep,setAiGStep]=useState(1)",
  "  const [aiGSub,setAiGSub]=useState('Physics')",
  "  const [aiGCnt,setAiGCnt]=useState('10')",
  "  const [aiGDiff,setAiGDiff]=useState('medium')",
  "  const [aiGLoading,setAiGLoading]=useState(false)",
  "  const [aiGResult,setAiGResult]=useState([])",
  "  const aiChR=useRef('');const aiTopR=useRef('');const qImageR=useRef('')"
].join('\n');
if(!t.includes(s1o)){console.error('ERROR: state anchor missing');process.exit(1)}
t = t.replace(s1o, s1n);
console.log('Step 1 done: states added');

// ── 2. UPDATE fQs ──────────────────────────────────────────
const s2o = [
  "  const fQs=(questions||[]).filter(q=>{",
  "    const mq=!qSearch||q.text?.toLowerCase().includes(qSearch.toLowerCase())||q.subject?.toLowerCase().includes(qSearch.toLowerCase())",
  "    const ms=qSubjFilter==='all'||q.subject===qSubjFilter",
  "    return mq&&ms",
  "  })"
].join('\n');
const s2n = [
  "  const fQs=(questions||[]).filter(q=>{",
  "    const mq=!qSearch||q.text?.toLowerCase().includes(qSearch.toLowerCase())||q.subject?.toLowerCase().includes(qSearch.toLowerCase())||q.chapter?.toLowerCase().includes(qSearch.toLowerCase())||q.topic?.toLowerCase().includes(qSearch.toLowerCase())",
  "    const ms=qSubjFilter==='all'||q.subject===qSubjFilter",
  "    const OS=['Physics','Chemistry','Biology','Math']",
  "    const sec=qSec==='all'||(qSec==='Other'?!OS.includes(q.subject||''):q.subject===qSec)",
  "    const bio=qSec!=='Biology'||qBioSub==='all'||(q.chapter||'').toLowerCase().includes(qBioSub.toLowerCase())||(q.topic||'').toLowerCase().includes(qBioSub.toLowerCase())",
  "    return mq&&ms&&sec&&bio",
  "  })"
].join('\n');
if(!t.includes(s2o)){console.error('ERROR: fQs anchor missing');process.exit(1)}
t = t.replace(s2o, s2n);
console.log('Step 2 done: fQs updated');

// ── 3. ADD FUNCTIONS ───────────────────────────────────────
const s3anchor = "  const addQ=useCallback(async()=>{";
const s3insert = [
  "  const editQF=async(id,data)=>{",
  "    setSavingEQ(true)",
  "    try{",
  "      const r=await fetch(API+'/api/questions/'+id,{method:'PUT',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify(data)})",
  "      if(r.ok){T('Question updated!');setEditQD(null);setTimeout(()=>fetchAll(),400)}",
  "      else{const e=await r.json().catch(()=>({}));T(e.message||'Update failed','e')}",
  "    }catch(ex){T(ex.message,'e')}",
  "    setSavingEQ(false)",
  "  }",
  "  const dupQF=async(q)=>{",
  "    const d={text:'[COPY] '+q.text,subject:q.subject,chapter:q.chapter,topic:q.topic,difficulty:q.difficulty,type:q.type,options:q.options}",
  "    try{",
  "      const r=await fetch(API+'/api/questions',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify(d)})",
  "      if(r.ok){T('Duplicated!');setTimeout(()=>fetchAll(),400)}else T('Failed','e')",
  "    }catch{T('Network error','e')}",
  "  }",
  "  const aiGF=async()=>{",
  "    const ch=aiChR.current,tp=aiTopR.current",
  "    if(!ch||!tp){T('Chapter aur Topic fill karo','e');return}",
  "    setAiGLoading(true)",
  "    try{",
  "      const r=await fetch(API+'/api/questions/generate',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify({subject:aiGSub,chapter:ch,topic:tp,count:parseInt(aiGCnt)||10,difficulty:aiGDiff})})",
  "      if(r.ok){const d=await r.json();const qs=d.questions||d.generated||[];setAiGResult(qs);T(qs.length+' generated!')}",
  "      else T('AI failed','e')",
  "    }catch{T('Network error','e')}",
  "    setAiGLoading(false)",
  "  }",
  "  const saveAiQs=async()=>{",
  "    if(!aiGResult.length)return",
  "    try{",
  "      const r=await fetch(API+'/api/questions/bulk-save',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify({questions:aiGResult})})",
  "      if(r.ok){T(aiGResult.length+' saved!');setAiGResult([]);setAiGO(false);setTimeout(()=>fetchAll(),400)}",
  "      else T('Save failed','e')",
  "    }catch{T('Network error','e')}",
  "  }",
  "  const blkDelQs=async()=>{",
  "    if(!bulkSel.length||!confirm('Delete '+bulkSel.length+' questions?'))return",
  "    for(const id of bulkSel){await fetch(API+'/api/questions/'+id,{method:'DELETE',headers:{Authorization:'Bearer '+token}})}",
  "    setQuestions(p=>p.filter(q=>!bulkSel.includes(q._id)));setBulkSel([]);T('Bulk deleted.')",
  "  }",
  "  const expQB=()=>{",
  "    const hdr='ID\\tText\\tSubject\\tChapter\\tDifficulty\\tType'",
  "    const rows=(questions||[]).map(function(q){return[q._id||'',q.text||'',q.subject||'',q.chapter||'',q.difficulty||'',q.type||''].join('\\t')})",
  "    const blob=new Blob([hdr+'\\n'+rows.join('\\n')],{type:'text/csv'})",
  "    const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='qbank.csv';a.click()",
  "  }",
  "  "
].join('\n');
if(!t.includes(s3anchor)){console.error('ERROR: addQ anchor missing');process.exit(1)}
t = t.replace(s3anchor, s3insert + s3anchor);
console.log('Step 3 done: functions added');

// ── 4. REPLACE QUESTIONS TAB JSX ──────────────────────────
const OLD_START = "          {/* ══ QUESTION BANK ══ */}\n          {tab==='questions'&&(\n            <div>";
const OLD_END   = "            </div>\n          )}\n\n          {/* ══ SMART GENERATOR ══ */}";

const si = t.indexOf(OLD_START);
const ei = t.indexOf(OLD_END, si);
if(si===-1){console.error('ERROR: QB start not found');process.exit(1)}
if(ei===-1){console.error('ERROR: QB end not found');process.exit(1)}
console.log('Found QB block at lines: start='+si+' end='+ei);

// Build JSX line by line using array to avoid any string literal issues
const JSX = [
"          {/* ══ QUESTION BANK ══ */}",
"          {tab==='questions'&&(",
"            <div style={{position:'relative'}}>",
"",
"              {qBV==='home'&&(",
"                <div>",
"                  <div style={{display:'flex',alignItems:'center',justifyContent:'space-between',marginBottom:20,flexWrap:'wrap',gap:10}}>",
"                    <div><div style={pageTitle}>📚 Question Bank</div><div style={pageSub}>{(questions||[]).length} questions · NEET Ready</div></div>",
"                    <button onClick={expQB} style={{...bg_,fontSize:11}}>⬇️ Export</button>",
"                  </div>",
"                  <div style={{display:'grid',gridTemplateColumns:'repeat(5,1fr)',gap:8,marginBottom:24}}>",
"                    {[{l:'Total',v:(questions||[]).length,c:'#A78BFA'},{l:'Physics',v:(questions||[]).filter(q=>q.subject==='Physics').length,c:'#60A5FA'},{l:'Chemistry',v:(questions||[]).filter(q=>q.subject==='Chemistry').length,c:'#F472B6'},{l:'Biology',v:(questions||[]).filter(q=>q.subject==='Biology').length,c:'#34D399'},{l:'Math',v:(questions||[]).filter(q=>q.subject==='Math').length,c:'#FBBF24'}].map(function(x){return(",
"                      <div key={x.l} style={{background:'rgba(255,255,255,0.04)',border:'1px solid '+x.c+'30',borderRadius:10,padding:'10px 6px',textAlign:'center'}}>",
"                        <div style={{fontSize:18,fontWeight:800,color:x.c}}>{x.v}</div>",
"                        <div style={{fontSize:9,color:'#64748b',marginTop:2}}>{x.l}</div>",
"                      </div>",
"                    )})}",
"                  </div>",
"                  <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:20,maxWidth:680,margin:'0 auto 28px'}}>",
"                    <div onClick={function(){setQBV('add')}} style={{cursor:'pointer',background:'linear-gradient(135deg,rgba(77,159,255,0.12),rgba(160,80,255,0.08))',border:'1.5px solid rgba(77,159,255,0.3)',borderRadius:20,padding:'28px 18px',textAlign:'center'}}>",
"                      <div style={{fontSize:40,marginBottom:10}}>➕</div>",
"                      <div style={{fontSize:16,fontWeight:800,color:'#E2E8F0',marginBottom:6}}>Add Question</div>",
"                      <div style={{fontSize:11,color:'#64748B',marginBottom:16}}>Manually add or AI auto-generate</div>",
"                      <div style={{display:'inline-block',background:'rgba(77,159,255,0.15)',border:'1px solid rgba(77,159,255,0.4)',borderRadius:8,padding:'7px 16px',fontSize:11,color:'#4D9FFF',fontWeight:700}}>Add Questions</div>",
"                    </div>",
"                    <div onClick={function(){setQBV('preview');setQSec('all')}} style={{cursor:'pointer',background:'linear-gradient(135deg,rgba(0,229,160,0.08),rgba(160,80,255,0.06))',border:'1.5px solid rgba(0,229,160,0.25)',borderRadius:20,padding:'28px 18px',textAlign:'center'}}>",
"                      <div style={{fontSize:40,marginBottom:10}}>👁️</div>",
"                      <div style={{fontSize:16,fontWeight:800,color:'#E2E8F0',marginBottom:6}}>Preview All Questions</div>",
"                      <div style={{fontSize:11,color:'#64748B',marginBottom:16}}>Browse, filter, edit section-wise</div>",
"                      <div style={{display:'inline-block',background:'rgba(0,229,160,0.12)',border:'1px solid rgba(0,229,160,0.35)',borderRadius:8,padding:'7px 16px',fontSize:11,color:'#00E5A0',fontWeight:700}}>Preview Bank</div>",
"                    </div>",
"                  </div>",
"                </div>",
"              )}",
"",
"              {qBV==='add'&&(",
"                <div>",
"                  <div style={{display:'flex',alignItems:'center',gap:12,marginBottom:20}}>",
"                    <button onClick={function(){setQBV('home')}} style={{...bg_,padding:'6px 14px',fontSize:12}}>Back</button>",
"                    <div><div style={pageTitle}>Add Question to Bank</div><div style={pageSub}>Fill all details</div></div>",
"                  </div>",
"                  <div style={cs}>",
"                    <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:12}}>",
"                      <div style={{gridColumn:'1/-1'}}><label style={lbl}>Question Text *</label><STextarea init='' onSet={function(v){qTxtR.current=v}} ph='Type question text…' rows={3} style={{...inp,resize:'vertical'}}/></div>",
"                      <div><label style={lbl}>Subject *</label><SSelect val={qSubj} onChange={setQSubj} opts={[{v:'Physics',l:'Physics'},{v:'Chemistry',l:'Chemistry'},{v:'Biology',l:'Biology'},{v:'Math',l:'Math'},{v:'Other',l:'Other'}]} style={{...inp}}/></div>",
"                      <div><label style={lbl}>Question Type</label><SSelect val={qType} onChange={setQType} opts={[{v:'SCQ',l:'SCQ'},{v:'MSQ',l:'MSQ'},{v:'Integer',l:'Integer'}]} style={{...inp}}/></div>",
"                      <div><label style={lbl}>Difficulty</label><SSelect val={qDiff} onChange={setQDiff} opts={[{v:'easy',l:'Easy'},{v:'medium',l:'Medium'},{v:'hard',l:'Hard'}]} style={{...inp}}/></div>",
"                      <div><label style={lbl}>Correct Answer</label><SSelect val={qAns} onChange={setQAns} opts={[{v:'A',l:'Option A'},{v:'B',l:'Option B'},{v:'C',l:'Option C'},{v:'D',l:'Option D'}]} style={{...inp}}/></div>",
"                      <div><label style={lbl}>Chapter</label><SInput init='' onSet={function(v){qChapR.current=v}} ph='e.g. Electrostatics' style={inp}/></div>",
"                      <div><label style={lbl}>Topic</label><SInput init='' onSet={function(v){qTopicR.current=v}} ph='e.g. Coulombs Law' style={inp}/></div>",
"                      {['SCQ','MSQ'].includes(qType)&&(",
"                        <>",
"                          <div><label style={lbl}>Option A</label><SInput init='' onSet={function(v){qA.current=v}} ph='Option A' style={inp}/></div>",
"                          <div><label style={lbl}>Option B</label><SInput init='' onSet={function(v){qB.current=v}} ph='Option B' style={inp}/></div>",
"                          <div><label style={lbl}>Option C</label><SInput init='' onSet={function(v){qC.current=v}} ph='Option C' style={inp}/></div>",
"                          <div><label style={lbl}>Option D</label><SInput init='' onSet={function(v){qD.current=v}} ph='Option D' style={inp}/></div>",
"                        </>",
"                      )}",
"                      <div style={{gridColumn:'1/-1'}}><label style={lbl}>Explanation</label><STextarea init='' onSet={function(v){qExpR.current=v}} ph='Explain the answer…' rows={2} style={{...inp,resize:'vertical'}}/></div>",
"                    </div>",
"                    <div style={{display:'flex',gap:10,marginTop:16}}>",
"                      <button onClick={addQ} disabled={savingQ} style={{...bp,flex:2,opacity:savingQ?0.7:1}}>{savingQ?'Saving…':'Add to Bank'}</button>",
"                      <button onClick={function(){qTxtR.current='';qA.current='';qB.current='';qC.current='';qD.current='';qChapR.current='';qTopicR.current='';qExpR.current='';T('Cleared')}} style={{...bg_}}>Clear</button>",
"                    </div>",
"                  </div>",
"                  <div onClick={function(){setAiGO(true);setAiGStep(1)}} style={{position:'fixed',bottom:90,right:16,width:62,height:62,borderRadius:'50%',background:'linear-gradient(135deg,#4D9FFF,#A855F7)',boxShadow:'0 0 20px rgba(168,85,247,0.5)',cursor:'pointer',display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center',zIndex:990}}>",
"                    <div style={{fontSize:18}}>🤖</div>",
"                    <div style={{fontSize:7,color:'#fff',fontWeight:700}}>AI GEN</div>",
"                  </div>",
"                </div>",
"              )}",
"",
"              {qBV==='preview'&&(",
"                <div>",
"                  <div style={{display:'flex',alignItems:'center',gap:10,marginBottom:12,flexWrap:'wrap'}}>",
"                    <button onClick={function(){setQBV('home');setBulkSel([])}} style={{...bg_,padding:'6px 12px',fontSize:12}}>Back</button>",
"                    <div style={{flex:1}}><div style={pageTitle}>Preview All Questions</div><div style={pageSub}>{fQs.length} of {(questions||[]).length} shown</div></div>",
"                    <button onClick={function(){setStdPrv(function(p){return !p})}} style={{...bg_,fontSize:11}}>{stdPrv?'Student ON':'Student View'}</button>",
"                    <button onClick={expQB} style={{...bg_,fontSize:11}}>Export</button>",
"                    <button onClick={function(){setQBV('add')}} style={{...bp,fontSize:11}}>Add</button>",
"                  </div>",
"                  <SInput init='' onSet={setQSearch} ph='Search questions…' style={{...inp,marginBottom:10}}/>",
"                  <div style={{display:'flex',gap:6,flexWrap:'wrap',marginBottom:8}}>",
"                    {[{k:'all',l:'All',col:'#A78BFA'},{k:'Physics',l:'Physics',col:'#60A5FA'},{k:'Chemistry',l:'Chem',col:'#F472B6'},{k:'Biology',l:'Bio',col:'#34D399'},{k:'Math',l:'Math',col:'#FBBF24'},{k:'Other',l:'Other',col:'#94A3B8'}].map(function(x){",
"                      const cnt=x.k==='all'?(questions||[]).length:x.k==='Other'?(questions||[]).filter(function(q){return !['Physics','Chemistry','Biology','Math'].includes(q.subject||'')}).length:(questions||[]).filter(function(q){return q.subject===x.k}).length",
"                      const isA=qSec===x.k",
"                      return(<button key={x.k} onClick={function(){setQSec(x.k);setQBioSub('all')}} style={{padding:'5px 11px',borderRadius:20,border:'1.5px solid '+(isA?x.col:x.col+'28'),background:isA?x.col+'18':'transparent',color:isA?x.col:'#64748B',fontSize:11,fontWeight:isA?700:400,cursor:'pointer'}}>{x.l} ({cnt})</button>)",
"                    })}",
"                  </div>",
"                  {qSec==='Biology'&&(",
"                    <div style={{display:'flex',gap:6,marginBottom:8}}>",
"                      {[{k:'all',l:'All Bio'},{k:'Zoology',l:'Zoology'},{k:'Botany',l:'Botany'}].map(function(x){",
"                        const isA=qBioSub===x.k",
"                        return(<button key={x.k} onClick={function(){setQBioSub(x.k)}} style={{padding:'4px 10px',borderRadius:14,border:'1px solid '+(isA?'#34D399':'rgba(52,211,153,0.2)'),background:isA?'rgba(52,211,153,0.15)':'transparent',color:isA?'#34D399':'#64748B',fontSize:10,cursor:'pointer'}}>{x.l}</button>)",
"                      })}",
"                    </div>",
"                  )}",
"                  {bulkSel.length>0&&(",
"                    <div style={{display:'flex',alignItems:'center',gap:10,padding:'9px 14px',background:'rgba(255,75,75,0.08)',border:'1px solid rgba(255,75,75,0.25)',borderRadius:10,marginBottom:12,flexWrap:'wrap'}}>",
"                      <span style={{fontSize:12,color:'#FC8181',fontWeight:700}}>{bulkSel.length} selected</span>",
"                      <button onClick={blkDelQs} style={{...bd,fontSize:11,padding:'4px 14px'}}>Delete Selected</button>",
"                      <button onClick={function(){setBulkSel([])}} style={{...bg_,fontSize:11}}>Clear</button>",
"                    </div>",
"                  )}",
"                  {fQs.length===0",
"                    ?<PageHero icon='❓' title='No Questions Found' subtitle='Try different search or section.'/>",
"                    :<div style={{display:'flex',flexDirection:'column',gap:8}}>",
"                      {fQs.map(function(q,qi){",
"                        const isChk=bulkSel.includes(q._id)",
"                        const sCol=q.subject==='Physics'?'#60A5FA':q.subject==='Chemistry'?'#F472B6':q.subject==='Biology'?'#34D399':q.subject==='Math'?'#FBBF24':'#94A3B8'",
"                        const dCol=q.difficulty==='hard'?'#FF4D4D':q.difficulty==='easy'?'#00C864':'#FFB300'",
"                        return(",
"                          <div key={q._id||qi} style={{...cs,marginBottom:0,borderLeft:'3px solid '+sCol+'50',background:isChk?'rgba(77,159,255,0.06)':undefined}}>",
"                            <div style={{display:'flex',alignItems:'flex-start',gap:10}}>",
"                              <input type='checkbox' checked={isChk} onChange={function(e){if(e.target.checked)setBulkSel(function(p){return [...p,q._id]});else setBulkSel(function(p){return p.filter(function(x){return x!==q._id})})}} style={{marginTop:4,cursor:'pointer'}}/>",
"                              <div style={{flex:1,minWidth:0}}>",
"                                <div style={{display:'flex',gap:5,marginBottom:5,flexWrap:'wrap'}}>",
"                                  <span style={{fontSize:10,color:'#4D9FFF',fontWeight:700}}>#{qi+1}</span>",
"                                  <Badge label={q.subject||'General'} col={sCol}/>",
"                                  <Badge label={q.difficulty||'?'} col={dCol}/>",
"                                  <Badge label={q.type||'SCQ'} col='#4D9FFF'/>",
"                                </div>",
"                                <div onClick={function(){setSelQId(q._id)}} style={{cursor:'pointer',fontSize:12,color:'#CBD5E1',lineHeight:1.6,marginBottom:4}}>{(q.text||'').slice(0,160)}{(q.text||'').length>160?'…':''}</div>",
"                                {q.chapter&&<div style={{fontSize:10,color:'#64748B'}}>Ch: {q.chapter}{q.topic?' > '+q.topic:''}</div>}",
"                              </div>",
"                              <div style={{display:'flex',gap:3,flexDirection:'column'}}>",
"                                <button onClick={function(){setSelQId(q._id)}} style={{...bg_,padding:'3px 7px',fontSize:10}}>👁️</button>",
"                                <button onClick={function(){setEditQD(Object.assign({},q))}} style={{...bg_,padding:'3px 7px',fontSize:10}}>✏️</button>",
"                                <button onClick={function(){dupQF(q)}} style={{...bg_,padding:'3px 7px',fontSize:10}}>📋</button>",
"                                <button onClick={async function(){if(confirm('Delete?')){const r=await fetch(API+'/api/questions/'+q._id,{method:'DELETE',headers:{Authorization:'Bearer '+token}});if(r.ok){setQuestions(function(p){return p.filter(function(x){return x._id!==q._id})});T('Deleted.')}else T('Failed','e')}}} style={{...bd,padding:'3px 7px',fontSize:10}}>🗑️</button>",
"                              </div>",
"                            </div>",
"                          </div>",
"                        )",
"                      })}",
"                    </div>",
"                  }",
"                </div>",
"              )}",
"",
"              {aiGO&&(",
"                <div style={{position:'fixed',inset:0,background:'rgba(0,0,0,0.85)',zIndex:1000,display:'flex',alignItems:'center',justifyContent:'center',padding:16}}>",
"                  <div style={{background:'#0D1B2A',border:'1px solid rgba(77,159,255,0.3)',borderRadius:20,padding:24,width:'100%',maxWidth:420,maxHeight:'90vh',overflowY:'auto'}}>",
"                    <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:14}}>",
"                      <div><div style={{fontSize:15,fontWeight:800,color:'#E2E8F0'}}>AI Question Generator</div><div style={{fontSize:11,color:'#64748B'}}>Step {aiGStep} of 4</div></div>",
"                      <button onClick={function(){setAiGO(false);setAiGStep(1);setAiGResult([])}} style={{...bg_,padding:'3px 9px',fontSize:12}}>X</button>",
"                    </div>",
"                    <div style={{display:'flex',gap:4,marginBottom:16}}>{[1,2,3,4].map(function(s){return(<div key={s} style={{flex:1,height:3,borderRadius:2,background:s<=aiGStep?'#4D9FFF':'rgba(255,255,255,0.1)'}}/>)})}</div>",
"                    {aiGStep===1&&(<div>",
"                      <div style={{fontSize:13,fontWeight:700,color:'#CBD5E1',marginBottom:12}}>Select Subject</div>",
"                      <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10}}>",
"                        {['Physics','Chemistry','Biology','Math'].map(function(v){return(",
"                          <div key={v} onClick={function(){setAiGSub(v);setAiGStep(2)}} style={{padding:'14px 10px',borderRadius:12,border:'1.5px solid rgba(77,159,255,0.3)',cursor:'pointer',textAlign:'center'}}>",
"                            <div style={{fontSize:12,fontWeight:700,color:'#CBD5E1'}}>{v}</div>",
"                          </div>",
"                        )})}",
"                      </div>",
"                    </div>)}",
"                    {aiGStep===2&&(<div>",
"                      <div style={{fontSize:13,fontWeight:700,color:'#CBD5E1',marginBottom:12}}>Enter Chapter</div>",
"                      <SInput init='' onSet={function(v){aiChR.current=v}} ph='e.g. Electrostatics' style={{...inp,marginBottom:14}}/>",
"                      <div style={{display:'flex',gap:8}}><button onClick={function(){setAiGStep(1)}} style={{...bg_,flex:1}}>Back</button><button onClick={function(){if(aiChR.current)setAiGStep(3);else T('Fill chapter','e')}} style={{...bp,flex:2}}>Next</button></div>",
"                    </div>)}",
"                    {aiGStep===3&&(<div>",
"                      <div style={{fontSize:13,fontWeight:700,color:'#CBD5E1',marginBottom:12}}>Enter Topic</div>",
"                      <SInput init='' onSet={function(v){aiTopR.current=v}} ph='e.g. Coulombs Law' style={{...inp,marginBottom:14}}/>",
"                      <div style={{display:'flex',gap:8}}><button onClick={function(){setAiGStep(2)}} style={{...bg_,flex:1}}>Back</button><button onClick={function(){if(aiTopR.current)setAiGStep(4);else T('Fill topic','e')}} style={{...bp,flex:2}}>Next</button></div>",
"                    </div>)}",
"                    {aiGStep===4&&(<div>",
"                      <div style={{fontSize:13,fontWeight:700,color:'#CBD5E1',marginBottom:12}}>Configure</div>",
"                      <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10,marginBottom:12}}>",
"                        <div><label style={lbl}>Count</label><SSelect val={aiGCnt} onChange={setAiGCnt} opts={[{v:'5',l:'5'},{v:'10',l:'10'},{v:'15',l:'15'},{v:'20',l:'20'}]} style={{...inp}}/></div>",
"                        <div><label style={lbl}>Difficulty</label><SSelect val={aiGDiff} onChange={setAiGDiff} opts={[{v:'easy',l:'Easy'},{v:'medium',l:'Medium'},{v:'hard',l:'Hard'}]} style={{...inp}}/></div>",
"                      </div>",
"                      <div style={{display:'flex',gap:8}}><button onClick={function(){setAiGStep(3)}} style={{...bg_,flex:1}}>Back</button><button onClick={aiGF} disabled={aiGLoading} style={{...bp,flex:2,opacity:aiGLoading?0.7:1}}>{aiGLoading?'Generating…':'Generate'}</button></div>",
"                    </div>)}",
"                    {aiGResult.length>0&&(",
"                      <div style={{marginTop:16}}>",
"                        <div style={{fontSize:12,fontWeight:700,color:'#00C864',marginBottom:8}}>{aiGResult.length} Generated!</div>",
"                        <button onClick={saveAiQs} style={{...bp,width:'100%'}}>Save All to Bank</button>",
"                      </div>",
"                    )}",
"                  </div>",
"                </div>",
"              )}",
"",
"              {selQId&&(function(){",
"                const qi=(questions||[]).findIndex(function(q){return q._id===selQId})",
"                const q=(questions||[])[qi]",
"                if(!q)return null",
"                const sCol=q.subject==='Physics'?'#60A5FA':q.subject==='Chemistry'?'#F472B6':q.subject==='Biology'?'#34D399':'#A78BFA'",
"                const dCol=q.difficulty==='hard'?'#FF4D4D':q.difficulty==='easy'?'#00C864':'#FFB300'",
"                return(",
"                  <div style={{position:'fixed',inset:0,background:'rgba(0,0,0,0.88)',zIndex:1000,display:'flex',alignItems:'center',justifyContent:'center',padding:16}}>",
"                    <div style={{background:'#0D1B2A',border:'1px solid rgba(77,159,255,0.2)',borderRadius:20,padding:22,width:'100%',maxWidth:500,maxHeight:'90vh',overflowY:'auto'}}>",
"                      <div style={{display:'flex',justifyContent:'space-between',marginBottom:12}}>",
"                        <div><div style={{display:'flex',gap:5,flexWrap:'wrap',marginBottom:4}}><Badge label={q.subject||'?'} col={sCol}/><Badge label={q.difficulty||'?'} col={dCol}/></div><div style={{fontSize:10,color:'#475569'}}>Q{qi+1} of {(questions||[]).length}</div></div>",
"                        <button onClick={function(){setSelQId(null)}} style={{...bg_,padding:'3px 9px',fontSize:12}}>X</button>",
"                      </div>",
"                      <div style={{fontSize:13,color:'#E2E8F0',lineHeight:1.7,marginBottom:12,padding:'12px 14px',background:'rgba(255,255,255,0.03)',borderRadius:10}}>{q.text}</div>",
"                      {(q.options||[]).length>0&&(",
"                        <div style={{display:'flex',flexDirection:'column',gap:6,marginBottom:12}}>",
"                          {(q.options||[]).map(function(opt,oi){",
"                            const ltr=String.fromCharCode(65+oi)",
"                            const isC=String(q.correct&&q.correct[0])===String(oi)||q.correctAnswer===ltr",
"                            return(<div key={oi} style={{padding:'8px 12px',borderRadius:8,border:'1px solid '+(isC?'rgba(0,200,100,0.4)':'rgba(255,255,255,0.07)'),background:isC?'rgba(0,200,100,0.08)':'rgba(255,255,255,0.02)'}}><span style={{fontWeight:700,color:isC?'#00C864':'#4D9FFF',marginRight:8}}>{ltr}.</span><span style={{fontSize:12,color:isC?'#E2E8F0':'#94A3B8'}}>{opt}</span>{isC&&<span style={{marginLeft:8,fontSize:10,color:'#00C864'}}>Correct</span>}</div>)",
"                          })}",
"                        </div>",
"                      )}",
"                      {q.explanation&&<div style={{fontSize:11,color:'#94A3B8',marginBottom:12}}>Explanation: {q.explanation}</div>}",
"                      <div style={{display:'flex',gap:8}}>",
"                        <button onClick={function(){if(qi>0)setSelQId((questions||[])[qi-1]._id)}} disabled={qi===0} style={{...bg_,flex:1,opacity:qi===0?0.4:1,fontSize:12}}>Prev</button>",
"                        <button onClick={function(){setEditQD(Object.assign({},q));setSelQId(null)}} style={{...bp,flex:1,fontSize:12}}>Edit</button>",
"                        <button onClick={function(){if(qi<(questions||[]).length-1)setSelQId((questions||[])[qi+1]._id)}} disabled={qi>=(questions||[]).length-1} style={{...bg_,flex:1,opacity:qi>=(questions||[]).length-1?0.4:1,fontSize:12}}>Next</button>",
"                      </div>",
"                    </div>",
"                  </div>",
"                )",
"              })()}",
"",
"              {editQD&&(",
"                <div style={{position:'fixed',inset:0,background:'rgba(0,0,0,0.88)',zIndex:1001,display:'flex',alignItems:'center',justifyContent:'center',padding:16}}>",
"                  <div style={{background:'#0D1B2A',border:'1px solid rgba(255,184,0,0.25)',borderRadius:20,padding:22,width:'100%',maxWidth:480,maxHeight:'90vh',overflowY:'auto'}}>",
"                    <div style={{display:'flex',justifyContent:'space-between',marginBottom:14}}>",
"                      <div style={{fontSize:14,fontWeight:800,color:'#E2E8F0'}}>Edit Question</div>",
"                      <button onClick={function(){setEditQD(null)}} style={{...bg_,padding:'3px 9px',fontSize:12}}>X</button>",
"                    </div>",
"                    <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10,marginBottom:14}}>",
"                      <div style={{gridColumn:'1/-1'}}><label style={lbl}>Question Text</label><textarea value={editQD.text||''} onChange={function(e){setEditQD(function(p){return Object.assign({},p,{text:e.target.value})})}} rows={3} style={{...inp,width:'100%',resize:'vertical'}}/></div>",
"                      <div><label style={lbl}>Subject</label><select value={editQD.subject||'Physics'} onChange={function(e){setEditQD(function(p){return Object.assign({},p,{subject:e.target.value})})}} style={{...inp,width:'100%'}}>{['Physics','Chemistry','Biology','Math','Other'].map(function(s){return(<option key={s} value={s}>{s}</option>)})}</select></div>",
"                      <div><label style={lbl}>Difficulty</label><select value={editQD.difficulty||'medium'} onChange={function(e){setEditQD(function(p){return Object.assign({},p,{difficulty:e.target.value})})}} style={{...inp,width:'100%'}}>{['easy','medium','hard'].map(function(d){return(<option key={d} value={d}>{d}</option>)})}</select></div>",
"                      <div><label style={lbl}>Chapter</label><input value={editQD.chapter||''} onChange={function(e){setEditQD(function(p){return Object.assign({},p,{chapter:e.target.value})})}} style={{...inp,width:'100%'}}/></div>",
"                      <div><label style={lbl}>Topic</label><input value={editQD.topic||''} onChange={function(e){setEditQD(function(p){return Object.assign({},p,{topic:e.target.value})})}} style={{...inp,width:'100%'}}/></div>",
"                      <div style={{gridColumn:'1/-1'}}><label style={lbl}>Explanation</label><textarea value={editQD.explanation||''} onChange={function(e){setEditQD(function(p){return Object.assign({},p,{explanation:e.target.value})})}} rows={2} style={{...inp,width:'100%',resize:'vertical'}}/></div>",
"                    </div>",
"                    <div style={{display:'flex',gap:8}}>",
"                      <button onClick={function(){setEditQD(null)}} style={{...bg_,flex:1}}>Cancel</button>",
"                      <button onClick={function(){editQF(editQD._id,editQD)}} disabled={savingEQ} style={{...bp,flex:2,opacity:savingEQ?0.7:1}}>{savingEQ?'Saving…':'Save Changes'}</button>",
"                    </div>",
"                  </div>",
"                </div>",
"              )}",
"",
"            </div>",
"          )}"
].join('\n');

t = t.slice(0, si) + JSX + '\n\n          {/* ══ SMART GENERATOR ══ */}' + t.slice(ei + OLD_END.length);
fs.writeFileSync(FILE, t);
console.log('Step 4 done: QB JSX replaced');
console.log('ALL DONE');
