const BASE="http://localhost:3000";
let passed=0,failed=0,superToken="",studentToken="",studentId="",examId="",attemptId="",questionId="";
async function req(m,path,b,t){const o={method:m,headers:{"Content-Type":"application/json"}};if(t)o.headers["Authorization"]="Bearer "+t;if(b)o.body=JSON.stringify(b);try{const r=await fetch(BASE+path,o);const x=await r.text();let j={};try{j=JSON.parse(x)}catch(_){}return{status:r.status,data:j,raw:x}}catch(e){return{status:0,data:{},raw:e.message}}}
function decode(t){try{return JSON.parse(Buffer.from(t.split(".")[1],"base64").toString())}catch(_){return{}}}
function log(n,nm,ok,d){const i=ok?"✅":"❌";if(ok)passed++;else failed++;console.log(i+" Step "+String(n).padStart(2,"0")+" | "+nm+(d?" → "+d:""))}
(async()=>{
console.log("\n====== ProveRank Stage 9 Phase 9.1 TEST ======\n");
let r,ok,list;
r=await req("POST","/api/auth/login",{email:"admin@proverank.com",password:"ProveRank@SuperAdmin123"});
ok=r.status===200&&r.data.token&&r.data.role==="superadmin";superToken=r.data.token||"";
log(1,"SuperAdmin Login",ok,"role="+r.data.role);
let p2=decode(superToken);log(2,"JWT Decode",p2.id&&p2.role==="superadmin","id="+p2.id);
r=await req("POST","/api/auth/login",{email:"student@proverank.com",password:"ProveRank@123"});
ok=r.status===200&&r.data.token&&r.data.role==="student";studentToken=r.data.token||"";
let sp=decode(studentToken);studentId=sp.id||"";
log(3,"Student Login",ok,"id="+studentId);
r=await req("GET","/api/auth/me",null,studentToken);
log(4,"GET auth/me",r.status===200,"status="+r.status);
r=await req("GET","/api/admin/admins",null,null);
log(5,"Role Protection",r.status===401||r.status===403,"status="+r.status);
r=await req("GET","/api/admin/admins",null,superToken);
ok=r.status===200;list=r.data.admins||r.data.students||r.data.data||r.data;
log(6,"GET All Students",ok,"count="+(Array.isArray(list)?list.length:"?"));
if(r.status!==200)console.log("   ->",r.raw.slice(0,150));
r=await req("POST","/api/exams",{title:"Stage9 Test Exam",subject:"NEET Full Mock",totalQuestions:10,totalMarks:40,duration:30,correctMarks:4,negativeMarks:1},superToken);
ok=r.status===200||r.status===201;examId=r.data._id||(r.data.exam&&r.data.exam._id)||"";
log(7,"Create Exam",ok,"examId="+examId);
r=await req("POST","/api/questions",{text:"Powerhouse of cell?",options:["Nucleus","Mitochondria","Ribosome","Golgi"],correctOption:1,subject:"Biology",difficulty:"Easy",chapter:"Cell Biology"},superToken);
ok=r.status===200||r.status===201;questionId=r.data._id||(r.data.question&&r.data.question._id)||"";
log(8,"Add Question",ok,"qId="+questionId);
r=await req("GET","/api/questions",null,superToken);
list=r.data.questions||r.data.data||r.data;
log(9,"GET Questions",r.status===200,"total="+(Array.isArray(list)?list.length:"?"));
r=await req("GET","/api/excel/template",null,superToken);
log(10,"Excel Route",r.status!==500,"status="+r.status);
r=await req("POST","/api/excel/upload",{},superToken);
log(11,"Excel Upload",r.status!==500&&r.status!==404,"status="+r.status);
r=await req("POST","/api/paper/generate-paper",{subject:"Biology",totalQuestions:5,difficulty:"Easy"},superToken);
log(12,"Test Generator",r.status!==500&&r.status!==404,"status="+r.status);
if(examId){r=await req("POST","/api/exams/"+examId+"/start-attempt",{},studentToken);ok=r.status===200||r.status===201;attemptId=r.data.attemptId||(r.data.attempt&&r.data.attempt._id)||r.data._id||"";log(13,"Start Attempt",ok,"attemptId="+attemptId);if(r.status!==200&&r.status!==201)console.log("   ->",r.raw.slice(0,150))}else log(13,"Start Attempt",false,"examId missing");
if(attemptId&&questionId){r=await req("PATCH","/api/attempts/"+attemptId+"/save-answer",{questionIndex:0,questionId:questionId,selectedOption:1},studentToken);log(14,"Save Answer",r.status===200||r.status===201,"status="+r.status);if(r.status!==200&&r.status!==201)console.log("   ->",r.raw.slice(0,150))}else log(14,"Save Answer",false,"missing ids");
if(attemptId){r=await req("POST","/api/attempts/"+attemptId+"/submit",{},studentToken);log(15,"Submit Exam",r.status===200||r.status===201,"status="+r.status)}else log(15,"Submit Exam",false,"missing");
if(attemptId){r=await req("POST","/api/results/"+attemptId+"/calculate",{},studentToken);if(r.status!==200)r=await req("GET","/api/results/"+attemptId,null,studentToken);log(16,"Result Calc",r.status===200,"score="+(r.data.score!=null?r.data.score:"?"));if(r.status!==200)console.log("   ->",r.raw.slice(0,150))}else log(16,"Result Calc",false,"missing");
r=await req("GET","/api/results/"+studentId,null,studentToken);
if(r.status!==200)r=await req("GET","/api/results/student/"+studentId,null,studentToken);
log(17,"Result History",r.status===200,"status="+r.status);if(r.status!==200)console.log("   ->",r.raw.slice(0,150));
let aid=attemptId||"000000000000000000000001";
r=await req("POST","/api/anticheat/"+aid+"/fullscreen-exit",{count:1},studentToken);
log(18,"AntiCheat",r.status!==500&&r.status!==404,"status="+r.status);
r=await req("POST","/api/webcam/snapshot",{attemptId:aid,imageData:"data:image/jpeg;base64,/9j/fake"},studentToken);
log(19,"Webcam Snapshot",r.status!==500&&r.status!==404,"status="+r.status);
r=await req("GET","/api/admin/stats/active-attempts",null,superToken);
log(20,"Dashboard Stats",r.status===200,"status="+r.status);
r=await req("GET","/api/admin/attempts",null,superToken);
log(21,"Active Attempts",r.status===200,"status="+r.status);
r=await req("GET","/api/admin/results/"+(examId||"aaaaaaaaaaaaaaaaaaaaaaaa")+"/leaderboard",null,superToken);
if(r.status!==200)r=await req("GET","/api/results/"+(examId||"aaaaaaaaaaaaaaaaaaaaaaaa")+"/leaderboard",null,superToken);
log(22,"Leaderboard",r.status===200,"status="+r.status);if(r.status!==200)console.log("   ->",r.raw.slice(0,150));
let last=0;for(let i=0;i<6;i++){r=await req("POST","/api/auth/login",{email:"x@x.com",password:"wrong"});last=r.status}
log(23,"Rate Limiter",last===429||last===400||last===401||last===403,"lastStatus="+last);
if(studentId){r=await req("POST","/api/admin/ban/"+studentId,{banReason:"Test",banType:"temporary",banExpiry:new Date(Date.now()+60000).toISOString()},superToken);log(24,"Ban Student",r.status===200,"status="+r.status);await req("POST","/api/admin/unban/"+studentId,{},superToken)}else log(24,"Ban/Unban",false,"missing");
r=await req("GET","/api/admin/permissions",null,superToken);
log(25,"Feature Flag",r.status!==500&&r.status!==404,"status="+r.status);
r=await req("GET","/api/admin/maintenance",null,superToken);
log(26,"Maintenance",r.status!==500&&r.status!==404,"status="+r.status);
if(questionId){r=await req("POST","/api/questions/"+questionId+"/ai/classify",{},superToken);log(27,"AI Question Tag",r.status!==500&&r.status!==404,"status="+r.status)}else log(27,"AI Question Tag",false,"missing");
r=await req("GET","/api/admin/activity-logs",null,superToken);
log(28,"Activity Logs",r.status!==500&&r.status!==404,"status="+r.status);if(r.status===404)console.log("   ->",r.raw.slice(0,150));
r=await req("GET","/api/auth/me",null,studentToken);
log(29,"Login History",r.status===200,"loginHistory="+(Array.isArray(r.data.loginHistory)?r.data.loginHistory.length:"N/A"));
if(examId){r=await req("POST","/api/exams/clone/"+examId,{},superToken);log(30,"Exam Clone",r.status===200||r.status===201,"status="+r.status);if(r.status!==200&&r.status!==201)console.log("   ->",r.raw.slice(0,150))}else log(30,"Exam Clone",false,"missing");
console.log("\n====== RESULTS: "+passed+"/30 PASSED  FAIL: "+failed+" ======\n");
})();
