#!/bin/bash
echo "=================================================="
echo "VERIFICATION — Feature 20B : Create Exam via Excel/CSV"
echo "Checks 20B.1 through 20B.46"
echo "=================================================="
cd ~/workspace || { echo "ERROR: ~/workspace not found"; exit 1; }
PASS=0
FAIL=0

if grep -qF "ExcelUploadZone" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 20B.1 — Excel/CSV upload zone for Create-Exam flow"; PASS=$((PASS+1)); else echo "  [❌] 20B.1 — Excel/CSV upload zone for Create-Exam flow — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "Download Template" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 20B.1.1 — Template download button"; PASS=$((PASS+1)); else echo "  [❌] 20B.1.1 — Template download button — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "Q_No','Question_Text','Hindi_Text" src/utils/excelParser.js 2>/dev/null; then echo "  [✅] 20B.1.2 — Template includes all canonical columns"; PASS=$((PASS+1)); else echo "  [❌] 20B.1.2 — Template includes all canonical columns — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "OptionsImage_URL" src/utils/excelParser.js 2>/dev/null; then echo "  [✅] 20B.1.2.14 — Template OptionsImage_URL column included"; PASS=$((PASS+1)); else echo "  [❌] 20B.1.2.14 — Template OptionsImage_URL column included — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "dragOver" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 20B.2 — Drag-drop upload zone UI"; PASS=$((PASS+1)); else echo "  [❌] 20B.2 — Drag-drop upload zone UI — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "excel/parse" frontend/app/admin/x7k2p/ContentForge.tsx src/routes/contentForge.js 2>/dev/null; then echo "  [✅] 20B.3 — Parse & validate (no save) preview step"; PASS=$((PASS+1)); else echo "  [❌] 20B.3 — Parse & validate (no save) preview step — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "Subject missing" src/utils/excelParser.js 2>/dev/null; then echo "  [✅] 20B.3.3 — Required field hard-validation (text+options+answer+subject)"; PASS=$((PASS+1)); else echo "  [❌] 20B.3.3 — Required field hard-validation (text+options+answer+subject) — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "parseCorrectAnswer" src/utils/excelParser.js 2>/dev/null; then echo "  [✅] 20B.3.4 — Correct_Answer parser SCQ/MSQ/Integer"; PASS=$((PASS+1)); else echo "  [❌] 20B.3.4 — Correct_Answer parser SCQ/MSQ/Integer — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "DuplicateCheckPanel" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 20B.3.7 — Duplicate-in-exam/batch check wired in UI"; PASS=$((PASS+1)); else echo "  [❌] 20B.3.7 — Duplicate-in-exam/batch check wired in UI — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "previewMode" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 20B.4 — Preview table — parsed rows / exam preview toggle"; PASS=$((PASS+1)); else echo "  [❌] 20B.4 — Preview table — parsed rows / exam preview toggle — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "moveQuestion" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 20B.4.5 — Re-order questions up/down arrows"; PASS=$((PASS+1)); else echo "  [❌] 20B.4.5 — Re-order questions up/down arrows — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "editingQ && editDraft" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 20B.4.6 — Edit individual row modal (text/options/subject/explanation/image)"; PASS=$((PASS+1)); else echo "  [❌] 20B.4.6 — Edit individual row modal (text/options/subject/explanation/image) — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "editDraft.explanation" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 20B.4.8 — Explanation editable in edit modal"; PASS=$((PASS+1)); else echo "  [❌] 20B.4.8 — Explanation editable in edit modal — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "ExamDetailsForm" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 20B.5 — Exam Details form (shared step)"; PASS=$((PASS+1)); else echo "  [❌] 20B.5 — Exam Details form (shared step) — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "Exam Title" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 20B.5.1 — Exam Title input"; PASS=$((PASS+1)); else echo "  [❌] 20B.5.1 — Exam Title input — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "totalQuestionsRequested" frontend/app/admin/x7k2p/ContentForge.tsx src/utils/examBuilder.js 2>/dev/null; then echo "  [✅] 20B.5.4 — Total Questions input (auto-select N of M parsed)"; PASS=$((PASS+1)); else echo "  [❌] 20B.5.4 — Total Questions input (auto-select N of M parsed) — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "subjectWiseCount" frontend/app/admin/x7k2p/ContentForge.tsx src/utils/examBuilder.js 2>/dev/null; then echo "  [✅] 20B.5.5 — Subject-wise Qs count distribution input"; PASS=$((PASS+1)); else echo "  [❌] 20B.5.5 — Subject-wise Qs count distribution input — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "duration: examD.duration" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 20B.5.7 — Duration field (named 'duration')"; PASS=$((PASS+1)); else echo "  [❌] 20B.5.7 — Duration field (named 'duration') — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "correctMarks" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null || grep -qF "negativeMarks" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 20B.5.9 — Marking scheme (correct/negative marks)"; PASS=$((PASS+1)); else echo "  [❌] 20B.5.9 — Marking scheme (correct/negative marks) — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "passwordEnabled" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 20B.5.13 — Password protection toggle"; PASS=$((PASS+1)); else echo "  [❌] 20B.5.13 — Password protection toggle — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "unlimitedAttempts" frontend/app/admin/x7k2p/ContentForge.tsx src/models/Exam.js 2>/dev/null; then echo "  [✅] 20B.5.16 — Unlimited attempts option"; PASS=$((PASS+1)); else echo "  [❌] 20B.5.16 — Unlimited attempts option — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "fromQNo" src/models/Exam.js src/utils/examBuilder.js 2>/dev/null || grep -qF "toQNo" src/models/Exam.js src/utils/examBuilder.js 2>/dev/null; then echo "  [✅] 20B.5.21 — Subject Q-No range mapping for live exam"; PASS=$((PASS+1)); else echo "  [❌] 20B.5.21 — Subject Q-No range mapping for live exam — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "subjectColor" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 20B.5.37 — Subject color bars in distribution UI"; PASS=$((PASS+1)); else echo "  [❌] 20B.5.37 — Subject color bars in distribution UI — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "AssignmentSelector" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 20B.6 — Assignment selector (Batch/Series/Mini/Individual)"; PASS=$((PASS+1)); else echo "  [❌] 20B.6 — Assignment selector (Batch/Series/Mini/Individual) — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "Test Series" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 20B.6.2 — Test Series dropdown"; PASS=$((PASS+1)); else echo "  [❌] 20B.6.2 — Test Series dropdown — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "multiBatchEnabled" frontend/app/admin/x7k2p/ContentForge.tsx src/models/Exam.js 2>/dev/null; then echo "  [✅] 20B.6.8 — Multi-batch assign toggle"; PASS=$((PASS+1)); else echo "  [❌] 20B.6.8 — Multi-batch assign toggle — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "excel/create-exam" frontend/app/admin/x7k2p/ContentForge.tsx src/routes/contentForge.js 2>/dev/null; then echo "  [✅] 20B.7 — Create Exam submit → backend builder"; PASS=$((PASS+1)); else echo "  [❌] 20B.7 — Create Exam submit → backend builder — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "examId: exam._id" src/routes/contentForge.js 2>/dev/null; then echo "  [✅] 20B.7.2 — Exam ID from response exam._id"; PASS=$((PASS+1)); else echo "  [❌] 20B.7.2 — Exam ID from response exam._id — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "PostCreateActions" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 20B.8 — Post-create actions step"; PASS=$((PASS+1)); else echo "  [❌] 20B.8 — Post-create actions step — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "scheduledPublishEnabled" frontend/app/admin/x7k2p/ContentForge.tsx src/models/Exam.js 2>/dev/null; then echo "  [✅] 20B.8.1 — Scheduled auto-publish toggle"; PASS=$((PASS+1)); else echo "  [❌] 20B.8.1 — Scheduled auto-publish toggle — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "isTemplate" frontend/app/admin/x7k2p/ContentForge.tsx src/models/Exam.js 2>/dev/null; then echo "  [✅] 20B.8.4 — Save as Template"; PASS=$((PASS+1)); else echo "  [❌] 20B.8.4 — Save as Template — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "will be notified" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 20B.8.6 — Notify Students toggle + count preview"; PASS=$((PASS+1)); else echo "  [❌] 20B.8.6 — Notify Students toggle + count preview — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "HEADER_SYNONYMS" src/utils/excelParser.js 2>/dev/null; then echo "  [✅] 20B.9 — Auto column-detect (header synonym mapping)"; PASS=$((PASS+1)); else echo "  [❌] 20B.9 — Auto column-detect (header synonym mapping) — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "Exam Created Successfully" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 20B.10 — Success screen + Copy Link + Create Another"; PASS=$((PASS+1)); else echo "  [❌] 20B.10 — Success screen + Copy Link + Create Another — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "google-sheet" src/routes/contentForge.js frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 20B.11 — Google Sheets URL import"; PASS=$((PASS+1)); else echo "  [❌] 20B.11 — Google Sheets URL import — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "answerSheetMap" src/utils/excelParser.js 2>/dev/null; then echo "  [✅] 20B.12 — Multi-sheet support (Answer/Explanation sheets)"; PASS=$((PASS+1)); else echo "  [❌] 20B.12 — Multi-sheet support (Answer/Explanation sheets) — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "Integer" src/utils/excelParser.js 2>/dev/null; then echo "  [✅] 20B.13 — MSQ/Integer type support in exam questions"; PASS=$((PASS+1)); else echo "  [❌] 20B.13 — MSQ/Integer type support in exam questions — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "Hindi_Text" src/utils/excelParser.js frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null || grep -qF "hindiOptions" src/utils/excelParser.js frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 20B.14 — Hindi bilingual fields support"; PASS=$((PASS+1)); else echo "  [❌] 20B.14 — Hindi bilingual fields support — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "imageUrl" src/utils/excelParser.js frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null || grep -qF "optionImages" src/utils/excelParser.js frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 20B.15 — Image URL + per-option image support"; PASS=$((PASS+1)); else echo "  [❌] 20B.15 — Image URL + per-option image support — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "PreSubmitChecklist" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 20B.16 — Pre-submit checklist before create"; PASS=$((PASS+1)); else echo "  [❌] 20B.16 — Pre-submit checklist before create — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "guessSubject" src/utils/excelParser.js 2>/dev/null || grep -qF "guessDifficulty" src/utils/excelParser.js 2>/dev/null; then echo "  [✅] 20B.17 — AI difficulty/subject auto-detect fallback"; PASS=$((PASS+1)); else echo "  [❌] 20B.17 — AI difficulty/subject auto-detect fallback — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "useIsMobile" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 20B.18 — Mobile-responsive layout (stacks on small screens)"; PASS=$((PASS+1)); else echo "  [❌] 20B.18 — Mobile-responsive layout (stacks on small screens) — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "'65%':'1fr'" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null || grep -qF "isMobile?'1fr':'65% 35%'" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 20B.19 — 65/35 desktop two-column layout"; PASS=$((PASS+1)); else echo "  [❌] 20B.19 — 65/35 desktop two-column layout — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "ExcelHome" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 20B.20 — Premium card-based ExcelHome (2 cards)"; PASS=$((PASS+1)); else echo "  [❌] 20B.20 — Premium card-based ExcelHome (2 cards) — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "status==='error'?'rgba" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 20B.30 — Color-coded valid/error preview rows"; PASS=$((PASS+1)); else echo "  [❌] 20B.30 — Color-coded valid/error preview rows — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "MathText" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 20B.40 — LaTeX/KaTeX rendering in preview"; PASS=$((PASS+1)); else echo "  [❌] 20B.40 — LaTeX/KaTeX rendering in preview — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "questionsOk={goodQs.length>0}" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 20B.43 — Pre-submit checklist (Qs/Title/Schedule/Assignment)"; PASS=$((PASS+1)); else echo "  [❌] 20B.43 — Pre-submit checklist (Qs/Title/Schedule/Assignment) — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "renderMath" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 20B.44 — LaTeX/KaTeX rendering (design requirement)"; PASS=$((PASS+1)); else echo "  [❌] 20B.44 — LaTeX/KaTeX rendering (design requirement) — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "qbView=\"ex_qs\" examView=\"ex_exam\"" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 20B.45 — ExcelHome 2-card structure (QB upload / Create Exam)"; PASS=$((PASS+1)); else echo "  [❌] 20B.45 — ExcelHome 2-card structure (QB upload / Create Exam) — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "backdropFilter:'blur" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 20B.46 — Premium Ultra SaaS design upgrade"; PASS=$((PASS+1)); else echo "  [❌] 20B.46 — Premium Ultra SaaS design upgrade — NOT FOUND"; FAIL=$((FAIL+1)); fi

echo ""
echo "=================================================="
echo "Feature 20B: $PASS passed / $FAIL missing (of $((PASS+FAIL)) checked)"
if [ $FAIL -eq 0 ]; then
  echo "✅✅✅ FEATURE 20B — ALL SUB-FEATURES VERIFIED PRESENT ✅✅✅"
else
  echo "⚠️  FEATURE 20B — $FAIL item(s) need attention (see ❌ above)"
fi
echo "=================================================="