#!/bin/bash
echo "=================================================="
echo "VERIFICATION — Feature 19B : Create Exam via Copy-Paste"
echo "Checks 19B.1 through 19B.38"
echo "=================================================="
cd ~/workspace || { echo "ERROR: ~/workspace not found"; exit 1; }
PASS=0
FAIL=0

if grep -qF "English Questions Text" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null || grep -qF "Hindi Questions Text" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.1.1 — Large textarea Paste Questions (Eng+Hindi 2 areas)"; PASS=$((PASS+1)); else echo "  [❌] 19B.1.1 — Large textarea Paste Questions (Eng+Hindi 2 areas) — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "Q-number" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null || grep -qF "numbered" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null || grep -qF "roman" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.1.2 — Format support Q1./Q1)/1./1) multi-format"; PASS=$((PASS+1)); else echo "  [❌] 19B.1.2 — Format support Q1./Q1)/1./1) multi-format — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "A-Da-d" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.1.3 — Options auto-detect (A)/A./a) multi-format"; PASS=$((PASS+1)); else echo "  [❌] 19B.1.3 — Options auto-detect (A)/A./a) multi-format — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "qText +=" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.1.4 — Multi-line question support (diagram description)"; PASS=$((PASS+1)); else echo "  [❌] 19B.1.4 — Multi-line question support (diagram description) — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "imageUrl" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.1.5 — Diagram-vale question paste support"; PASS=$((PASS+1)); else echo "  [❌] 19B.1.5 — Diagram-vale question paste support — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "chars</span>" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.1.6 — Character counter live"; PASS=$((PASS+1)); else echo "  [❌] 19B.1.6 — Character counter live — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "🗑️ Clear" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null || grep -qF "Clear" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.1.7 — Clear button"; PASS=$((PASS+1)); else echo "  [❌] 19B.1.7 — Clear button — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "parseSubjectMap" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.1B.1 — Subject allotment many formats (Q1. Physics etc)"; PASS=$((PASS+1)); else echo "  [❌] 19B.1B.1 — Subject allotment many formats (Q1. Physics etc) — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "Q?\s*(\d+)\s*-\s*Q" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.1B.2 — Subject range format Q1-Q45 Physics"; PASS=$((PASS+1)); else echo "  [❌] 19B.1B.2 — Subject range format Q1-Q45 Physics — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "Explanations.*optional" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null || grep -qF "parseExplanations" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.1C — Separate explanation textarea, auto-sync by Qno"; PASS=$((PASS+1)); else echo "  [❌] 19B.1C — Separate explanation textarea, auto-sync by Qno — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "Answer Key —" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.2.1 — Separate Answer Key textarea"; PASS=$((PASS+1)); else echo "  [❌] 19B.2.1 — Separate Answer Key textarea — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "parseAnswerKey" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.2.2 — Answer format 1-A,2-C / 1.A 2.C / one-per-line"; PASS=$((PASS+1)); else echo "  [❌] 19B.2.2 — Answer format 1-A,2-C / 1.A 2.C / one-per-line — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "ansMap[" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null || grep -qF "answerMap[" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.2.3 — Auto-sync Q number wise"; PASS=$((PASS+1)); else echo "  [❌] 19B.2.3 — Auto-sync Q number wise — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "MSQ" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.2.4 — MSQ support 1-AB / 1-(A,B)"; PASS=$((PASS+1)); else echo "  [❌] 19B.2.4 — MSQ support 1-AB / 1-(A,B) — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "Integer" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.2.5 — Integer type support 1-72, 2-0.25"; PASS=$((PASS+1)); else echo "  [❌] 19B.2.5 — Integer type support 1-72, 2-0.25 — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "splitIntoBlocks" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.3.1 — Question number wise auto-parsing Q1,Q2 detect"; PASS=$((PASS+1)); else echo "  [❌] 19B.3.1 — Question number wise auto-parsing Q1,Q2 detect — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "optionLineRe" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null || grep -qF "options.push" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.3.4 — Options A/B/C/D auto-separate per question"; PASS=$((PASS+1)); else echo "  [❌] 19B.3.4 — Options A/B/C/D auto-separate per question — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "explMap[base.num]" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.3.3 — Answer key & Explanation auto-sync with question numbers"; PASS=$((PASS+1)); else echo "  [❌] 19B.3.3 — Answer key & Explanation auto-sync with question numbers — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "hasError" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.3.5 — Validation & error highlighting (red)"; PASS=$((PASS+1)); else echo "  [❌] 19B.3.5 — Validation & error highlighting (red) — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "Answer missing for Q" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.3.6 — Missing answer highlight per question number"; PASS=$((PASS+1)); else echo "  [❌] 19B.3.6 — Missing answer highlight per question number — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "Detected</span>" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null || grep -qF "parsedQs.length} Detected" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.3.7 — Total questions detected count live counter"; PASS=$((PASS+1)); else echo "  [❌] 19B.3.7 — Total questions detected count live counter — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "errQs" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.3.8 — Parse errors list (Q numbers failed)"; PASS=$((PASS+1)); else echo "  [❌] 19B.3.8 — Parse errors list (Q numbers failed) — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "previewMode" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null || grep -qF "All Parsed Qs" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.4.1 — 2 Preview tables toggle (Parsed/Live Exam)"; PASS=$((PASS+1)); else echo "  [❌] 19B.4.1 — 2 Preview tables toggle (Parsed/Live Exam) — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "previewMode==='parsed'" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.4.1b — Full preview of all parsed questions"; PASS=$((PASS+1)); else echo "  [❌] 19B.4.1b — Full preview of all parsed questions — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "correct.includes(j)" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.4.2 — Each Q: text+4 options+correct(green)+explanation"; PASS=$((PASS+1)); else echo "  [❌] 19B.4.2 — Each Q: text+4 options+correct(green)+explanation — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "editingQ && editDraft" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null || grep -qF "Image URL" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.4.3 — Edit individual question per-Q modal w/ image url"; PASS=$((PASS+1)); else echo "  [❌] 19B.4.3 — Edit individual question per-Q modal w/ image url — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "setParsedQs(prev=>prev.filter" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.4.4 — Delete individual / Replace from QsBank"; PASS=$((PASS+1)); else echo "  [❌] 19B.4.4 — Delete individual / Replace from QsBank — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "moveQuestion" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.4.5 — Re-order questions (drag or up/down arrows)"; PASS=$((PASS+1)); else echo "  [❌] 19B.4.5 — Re-order questions (drag or up/down arrows) — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "goodQs.length" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.4.6 — Total count confirm"; PASS=$((PASS+1)); else echo "  [❌] 19B.4.6 — Total count confirm — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "DuplicateCheckPanel" frontend/app/admin/x7k2p/ContentForge.tsx src/routes/contentForge.js 2>/dev/null || grep -qF "check-duplicates" frontend/app/admin/x7k2p/ContentForge.tsx src/routes/contentForge.js 2>/dev/null; then echo "  [✅] 19B.4.7 — Duplicate detection (same exam paper)"; PASS=$((PASS+1)); else echo "  [❌] 19B.4.7 — Duplicate detection (same exam paper) — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "Exam Title" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.5.1 — Exam Title input required"; PASS=$((PASS+1)); else echo "  [❌] 19B.5.1 — Exam Title input required — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "'Physics','Chemistry','Biology'" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.5.2 — Subject dropdown"; PASS=$((PASS+1)); else echo "  [❌] 19B.5.2 — Subject dropdown — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "Mini Test" frontend/app/admin/x7k2p/ContentForge.tsx src/models/Exam.js 2>/dev/null; then echo "  [✅] 19B.5.3 — Category dropdown (Full Mock/Chapter/Part/Grand/Mini)"; PASS=$((PASS+1)); else echo "  [❌] 19B.5.3 — Category dropdown (Full Mock/Chapter/Part/Grand/Mini) — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "totalQuestionsRequested" frontend/app/admin/x7k2p/ContentForge.tsx src/utils/examBuilder.js 2>/dev/null; then echo "  [✅] 19B.5.4 — Total Question input - auto select N of M parsed"; PASS=$((PASS+1)); else echo "  [❌] 19B.5.4 — Total Question input - auto select N of M parsed — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "subjectWiseCount" frontend/app/admin/x7k2p/ContentForge.tsx src/utils/examBuilder.js 2>/dev/null; then echo "  [✅] 19B.5.5 — Subject wise Qs count input field"; PASS=$((PASS+1)); else echo "  [❌] 19B.5.5 — Subject wise Qs count input field — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "examType" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null || grep -qF "Exam Format" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.5.6 — Exam Type NEET/JEE/Custom"; PASS=$((PASS+1)); else echo "  [❌] 19B.5.6 — Exam Type NEET/JEE/Custom — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "duration: examD.duration" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.5.7 — Duration field named duration (not totalDurationSec)"; PASS=$((PASS+1)); else echo "  [❌] 19B.5.7 — Duration field named duration (not totalDurationSec) — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "Total Marks" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.5.8 — Total Marks"; PASS=$((PASS+1)); else echo "  [❌] 19B.5.8 — Total Marks — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "correctMarks" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null || grep -qF "negativeMarks" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.5.9 — Marking scheme correct/negative marks"; PASS=$((PASS+1)); else echo "  [❌] 19B.5.9 — Marking scheme correct/negative marks — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "Start Date" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.5.10 — Start Date & Time"; PASS=$((PASS+1)); else echo "  [❌] 19B.5.10 — Start Date & Time — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "End Date" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.5.11 — End Date & Time"; PASS=$((PASS+1)); else echo "  [❌] 19B.5.11 — End Date & Time — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "Custom Instructions" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.5.12 — Custom Instructions textarea"; PASS=$((PASS+1)); else echo "  [❌] 19B.5.12 — Custom Instructions textarea — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "passwordEnabled" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null || grep -qF "Password Protect" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.5.13 — Password Protection toggle+input"; PASS=$((PASS+1)); else echo "  [❌] 19B.5.13 — Password Protection toggle+input — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "whitelistEnabled" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.5.14 — Whitelist toggle"; PASS=$((PASS+1)); else echo "  [❌] 19B.5.14 — Whitelist toggle — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "waitingRoomEnabled" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null || grep -qF "waitingRoomMinutes" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.5.15 — Waiting Room toggle+minutes"; PASS=$((PASS+1)); else echo "  [❌] 19B.5.15 — Waiting Room toggle+minutes — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "unlimitedAttempts" frontend/app/admin/x7k2p/ContentForge.tsx src/models/Exam.js 2>/dev/null; then echo "  [✅] 19B.5.16 — Re-attempt control with Unlimited Attempt option"; PASS=$((PASS+1)); else echo "  [❌] 19B.5.16 — Re-attempt control with Unlimited Attempt option — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "reviewWindowEnabled" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.5.17 — Review Window toggle"; PASS=$((PASS+1)); else echo "  [❌] 19B.5.17 — Review Window toggle — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "sectionWiseEnabled" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.5.18 — Section Wise toggle"; PASS=$((PASS+1)); else echo "  [❌] 19B.5.18 — Section Wise toggle — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "watermark" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.5.19 — Watermark toggle"; PASS=$((PASS+1)); else echo "  [❌] 19B.5.19 — Watermark toggle — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "customInstructions" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.5.20 — Custom Instructions textarea (dup)"; PASS=$((PASS+1)); else echo "  [❌] 19B.5.20 — Custom Instructions textarea (dup) — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "fromQNo" src/models/Exam.js src/utils/examBuilder.js 2>/dev/null || grep -qF "toQNo" src/models/Exam.js src/utils/examBuilder.js 2>/dev/null; then echo "  [✅] 19B.5.21 — Q.No range to Subject mapping for live exam"; PASS=$((PASS+1)); else echo "  [❌] 19B.5.21 — Q.No range to Subject mapping for live exam — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "Assign to Batch" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.6.1 — Assign to Batch existing dropdown"; PASS=$((PASS+1)); else echo "  [❌] 19B.6.1 — Assign to Batch existing dropdown — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "Test Series" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.6.2 — Add to Test Series dropdown"; PASS=$((PASS+1)); else echo "  [❌] 19B.6.2 — Add to Test Series dropdown — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "Mini Test" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.6.3 — Add to Mini Test Series dropdown"; PASS=$((PASS+1)); else echo "  [❌] 19B.6.3 — Add to Mini Test Series dropdown — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "Individual / Open" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null || grep -qF "individual" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.6.4 — Individual/Open option"; PASS=$((PASS+1)); else echo "  [❌] 19B.6.4 — Individual/Open option — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "batches.map" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.6.5 — Batch dropdown"; PASS=$((PASS+1)); else echo "  [❌] 19B.6.5 — Batch dropdown — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "seriesList" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.6.7 — Test Series dropdown (S5)"; PASS=$((PASS+1)); else echo "  [❌] 19B.6.7 — Test Series dropdown (S5) — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "multiBatchEnabled" frontend/app/admin/x7k2p/ContentForge.tsx src/models/Exam.js 2>/dev/null; then echo "  [✅] 19B.6.8 — Multi-batch assign toggle"; PASS=$((PASS+1)); else echo "  [❌] 19B.6.8 — Multi-batch assign toggle — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "questions: inserted.map" src/utils/examBuilder.js 2>/dev/null; then echo "  [✅] 19B.7.1 — Creates exam with questions[]"; PASS=$((PASS+1)); else echo "  [❌] 19B.7.1 — Creates exam with questions[] — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "examId: exam._id" src/routes/contentForge.js 2>/dev/null || grep -qF "exam, examId" src/routes/contentForge.js 2>/dev/null; then echo "  [✅] 19B.7.2 — Exam ID from response exam._id (not d._id)"; PASS=$((PASS+1)); else echo "  [❌] 19B.7.2 — Exam ID from response exam._id (not d._id) — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "postCreate?.status" src/utils/examBuilder.js 2>/dev/null; then echo "  [✅] 19B.7.3 — Do NOT send status field, backend auto-draft"; PASS=$((PASS+1)); else echo "  [❌] 19B.7.3 — Do NOT send status field, backend auto-draft — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "inserted.map(d => d._id)" src/utils/examBuilder.js 2>/dev/null; then echo "  [✅] 19B.7.4 — After exam create, questions link to exam ID"; PASS=$((PASS+1)); else echo "  [❌] 19B.7.4 — After exam create, questions link to exam ID — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "Exam Created Successfully" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null || grep -qF "Back to All Exams" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.7.5 — Success toast + redirect to All Exams"; PASS=$((PASS+1)); else echo "  [❌] 19B.7.5 — Success toast + redirect to All Exams — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "scheduledPublishEnabled" frontend/app/admin/x7k2p/ContentForge.tsx src/models/Exam.js 2>/dev/null; then echo "  [✅] 19B.8.1 — Scheduled auto-publish toggle+input"; PASS=$((PASS+1)); else echo "  [❌] 19B.8.1 — Scheduled auto-publish toggle+input — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "publishNow" frontend/app/admin/x7k2p/ContentForge.tsx src/routes/contentForge.js 2>/dev/null || grep -qF "/publish" frontend/app/admin/x7k2p/ContentForge.tsx src/routes/contentForge.js 2>/dev/null; then echo "  [✅] 19B.8.2 — Publish Now button draft->published"; PASS=$((PASS+1)); else echo "  [❌] 19B.8.2 — Publish Now button draft->published — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "draft" src/models/Exam.js 2>/dev/null; then echo "  [✅] 19B.8.3 — Save as Draft (exam remains draft)"; PASS=$((PASS+1)); else echo "  [❌] 19B.8.3 — Save as Draft (exam remains draft) — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "isTemplate" frontend/app/admin/x7k2p/ContentForge.tsx src/models/Exam.js src/routes/contentForge.js 2>/dev/null; then echo "  [✅] 19B.8.4 — Save as Template"; PASS=$((PASS+1)); else echo "  [❌] 19B.8.4 — Save as Template — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "Copy Exam Link" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null || grep -qF "examLink" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.8.5 — Exam link copy shareable URL"; PASS=$((PASS+1)); else echo "  [❌] 19B.8.5 — Exam link copy shareable URL — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "notifyStudents" frontend/app/admin/x7k2p/ContentForge.tsx src/models/Exam.js src/utils/examBuilder.js 2>/dev/null; then echo "  [✅] 19B.8.6 — Notify Students toggle"; PASS=$((PASS+1)); else echo "  [❌] 19B.8.6 — Notify Students toggle — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "exam-review" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null || grep -qF "Countdown" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.8.7 — Exam Countdown page auto-generate"; PASS=$((PASS+1)); else echo "  [❌] 19B.8.7 — Exam Countdown page auto-generate — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "seriesName" frontend/app/admin/x7k2p/ContentForge.tsx src/models/Exam.js 2>/dev/null; then echo "  [✅] 19B.8.8 — Exam series/group linking"; PASS=$((PASS+1)); else echo "  [❌] 19B.8.8 — Exam series/group linking — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "roman" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.9 — Format auto-detect (numbered/bulleted/roman)"; PASS=$((PASS+1)); else echo "  [❌] 19B.9 — Format auto-detect (numbered/bulleted/roman) — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "guessDifficulty" src/utils/examBuilder.js frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.9B — Difficulty auto-tag AI suggest"; PASS=$((PASS+1)); else echo "  [❌] 19B.9B — Difficulty auto-tag AI suggest — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "Smart Clean" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null || grep -qF "smartClean" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.10 — Smart Clean button"; PASS=$((PASS+1)); else echo "  [❌] 19B.10 — Smart Clean button — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "{parsedQs.length} Detected" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.11 — Question count validator color warning"; PASS=$((PASS+1)); else echo "  [❌] 19B.11 — Question count validator color warning — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "Auto-calc" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.12 — Marks auto-calculate"; PASS=$((PASS+1)); else echo "  [❌] 19B.12 — Marks auto-calculate — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "WhatsApp-bold" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.13 — Import from WhatsApp format parser"; PASS=$((PASS+1)); else echo "  [❌] 19B.13 — Import from WhatsApp format parser — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "customDelim" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.14 — Split at custom delimiter"; PASS=$((PASS+1)); else echo "  [❌] 19B.14 — Split at custom delimiter — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "setEngText" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null || grep -qF "engText" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.15 — Re-paste to fix errors"; PASS=$((PASS+1)); else echo "  [❌] 19B.15 — Re-paste to fix errors — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "will be notified" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.16 — Batch Notification preview X students"; PASS=$((PASS+1)); else echo "  [❌] 19B.16 — Batch Notification preview X students — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "Copy Exam Link" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.17 — Exam ID auto-copy after create"; PASS=$((PASS+1)); else echo "  [❌] 19B.17 — Exam ID auto-copy after create — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "DuplicateCheckPanel" frontend/app/admin/x7k2p/ContentForge.tsx src/routes/contentForge.js 2>/dev/null || grep -qF "inSameBatch" frontend/app/admin/x7k2p/ContentForge.tsx src/routes/contentForge.js 2>/dev/null; then echo "  [✅] 19B.18 — Duplicate in exam check (same batch)"; PASS=$((PASS+1)); else echo "  [❌] 19B.18 — Duplicate in exam check (same batch) — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "65%" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.19.1 — Left panel 65% step-by-step form"; PASS=$((PASS+1)); else echo "  [❌] 19B.19.1 — Left panel 65% step-by-step form — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "35%" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.19.2 — Right panel 35% live preview toggle"; PASS=$((PASS+1)); else echo "  [❌] 19B.19.2 — Right panel 35% live preview toggle — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "Step 1-2" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null || grep -qF "Step —" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.20 — Step progress bar 6 steps purple active"; PASS=$((PASS+1)); else echo "  [❌] 19B.20 — Step progress bar 6 steps purple active — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "previewMode" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.21 — Toggle for all-pasted-Qs preview modal w/ summary cards"; PASS=$((PASS+1)); else echo "  [❌] 19B.21 — Toggle for all-pasted-Qs preview modal w/ summary cards — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "0A1628" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null || grep -qF "rgba(0,22,40" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.22 — Textarea dark bg #0A1628 monospace style"; PASS=$((PASS+1)); else echo "  [❌] 19B.22 — Textarea dark bg #0A1628 monospace style — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "placeholder=\"Q1" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.23 — Placeholder shows expected format with example"; PASS=$((PASS+1)); else echo "  [❌] 19B.23 — Placeholder shows expected format with example — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "Detected</span>" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.24 — Live detected count badge green top-right"; PASS=$((PASS+1)); else echo "  [❌] 19B.24 — Live detected count badge green top-right — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "color:C.acc, fontWeight:800" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.25 — Success row green border purple Q badge green chip"; PASS=$((PASS+1)); else echo "  [❌] 19B.25 — Success row green border purple Q badge green chip — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "rgba(255,77,77" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.26 — Error row red border Parse Failed badge"; PASS=$((PASS+1)); else echo "  [❌] 19B.26 — Error row red border Parse Failed badge — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "@keyframes shimmer" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.27 — Animated line-by-line appearance"; PASS=$((PASS+1)); else echo "  [❌] 19B.27 — Animated line-by-line appearance — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "type=\"range\" min={10} max={360}" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.28 — Duration slider+number combined"; PASS=$((PASS+1)); else echo "  [❌] 19B.28 — Duration slider+number combined — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "subjectColor" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.29 — Section toggle colored bars per subject"; PASS=$((PASS+1)); else echo "  [❌] 19B.29 — Section toggle colored bars per subject — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "cards.map(c=>" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.30 — 4 large clickable assignment cards"; PASS=$((PASS+1)); else echo "  [❌] 19B.30 — 4 large clickable assignment cards — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "boxShadow:a.assignmentType" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.31 — Selected card blue border+glow+checkmark"; PASS=$((PASS+1)); else echo "  [❌] 19B.31 — Selected card blue border+glow+checkmark — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "studentCount" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.32 — Batch dropdown shows student count"; PASS=$((PASS+1)); else echo "  [❌] 19B.32 — Batch dropdown shows student count — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "linear-gradient(135deg,#4D9FFF" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.33 — Create Exam button large purple gradient full-width"; PASS=$((PASS+1)); else echo "  [❌] 19B.33 — Create Exam button large purple gradient full-width — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "S.bg" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.34 — Save as Draft outlined secondary button"; PASS=$((PASS+1)); else echo "  [❌] 19B.34 — Save as Draft outlined secondary button — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "PreSubmitChecklist" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.35 — Pre-submit checklist Qs/Answer/Title/Date/Batch"; PASS=$((PASS+1)); else echo "  [❌] 19B.35 — Pre-submit checklist Qs/Answer/Title/Date/Batch — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "MathText" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null || grep -qF "renderMath" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null || grep -qF "katex" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.36 — LaTeX/KaTeX rendering"; PASS=$((PASS+1)); else echo "  [❌] 19B.36 — LaTeX/KaTeX rendering — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "CopyPasteHome" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null || grep -qF "qbView=\"cp_qs\" examView=\"cp_exam\"" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.37 — ContentForge home 2-card structure + Create Exam full feature"; PASS=$((PASS+1)); else echo "  [❌] 19B.37 — ContentForge home 2-card structure + Create Exam full feature — NOT FOUND"; FAIL=$((FAIL+1)); fi
if grep -qF "backdropFilter:'blur" frontend/app/admin/x7k2p/ContentForge.tsx 2>/dev/null; then echo "  [✅] 19B.38 — Premium Ultra SaaS design upgrade"; PASS=$((PASS+1)); else echo "  [❌] 19B.38 — Premium Ultra SaaS design upgrade — NOT FOUND"; FAIL=$((FAIL+1)); fi

echo ""
echo "=================================================="
echo "Feature 19B: $PASS passed / $FAIL missing (of $((PASS+FAIL)) checked)"
if [ $FAIL -eq 0 ]; then
  echo "✅✅✅ FEATURE 19B — ALL SUB-FEATURES VERIFIED PRESENT ✅✅✅"
else
  echo "⚠️  FEATURE 19B — $FAIL item(s) need attention (see ❌ above)"
fi
echo "=================================================="