'use client'
import { useState, useEffect } from 'react'

export function useThemeVars(darkMode: boolean) {
  return {
    bg:          darkMode ? 'radial-gradient(ellipse at 20% 50%,#001628 0%,#000A18 60%,#000510 100%)'
                          : 'radial-gradient(ellipse at 20% 50%,#E8F4FF 0%,#C9E0FF 60%,#A8CCFF 100%)',
    cardBg:      darkMode ? 'rgba(0,22,40,0.78)'       : 'rgba(255,255,255,0.85)',
    cardBorder:  darkMode ? 'rgba(77,159,255,0.22)'    : 'rgba(77,159,255,0.35)',
    textMain:    darkMode ? '#E8F4FF'                  : '#0F172A',
    textSub:     darkMode ? '#6B8BAF'                  : '#475569',
    inputBg:     darkMode ? 'rgba(0,22,40,0.85)'       : 'rgba(255,255,255,0.9)',
    inputBorder: darkMode ? '#002D55'                  : '#CBD5E1',
    inputColor:  darkMode ? '#E8F4FF'                  : '#0F172A',
    sidebarBg:   darkMode ? 'rgba(0,10,24,0.95)'       : 'rgba(248,252,255,0.95)',
    tableRowHover:darkMode? 'rgba(77,159,255,0.05)'    : 'rgba(77,159,255,0.04)',
    borderColor: darkMode ? 'rgba(77,159,255,0.12)'    : 'rgba(77,159,255,0.2)',
    mutedText:   darkMode ? '#3A5A7A'                  : '#94A3B8',
  }
}

export const EN_TEXTS = {
  // Nav
  home:'Home', features:'Features', results:'Results', pricing:'Pricing',
  login:'Login', logout:'Logout', register:'Register', dashboard:'Dashboard',
  profile:'Profile', exams:'Exams', leaderboard:'Leaderboard',
  analytics:'Analytics', certificate:'Certificate', settings:'Settings',
  notifications:'Notifications', admitCard:'Admit Card',
  // Landing
  heroTitle:"India's Most Advanced\nNEET Test Platform",
  heroSub:'Real rankings. Real results. No compromise on performance or integrity.',
  startFree:'Start Free Test', viewDemo:'Watch Demo',
  stat1v:'50,000+', stat1l:'Students',
  stat2v:'1,20,000+', stat2l:'Tests Taken',
  stat3v:'99.9%', stat3l:'Uptime',
  stat4v:'#1', stat4l:'NEET Platform',
  featuresTitle:'Everything You Need to Crack NEET',
  ctaLine:'Start your NEET journey today.',
  regFree:'Register Free →',
  // Auth
  loginTitle:'Welcome Back', loginSub:'Login to your account',
  emailLabel:'EMAIL / ROLL NUMBER', emailPlaceholder:'student@proverank.com',
  passLabel:'PASSWORD', passPlaceholder:'Enter your password',
  forgot:'Forgot password?', loginBtn:'Login →',
  loading:'Logging in...', noAcc:"Don't have an account?",
  regTitle:'Create Your Account', regSub:'Join ProveRank today',
  nameLabel:'FULL NAME', phoneLabel:'MOBILE NUMBER',
  otpLabel:'OTP (6 digits)', otpSent:'OTP sent to your number',
  regBtn:'Create Account →', haveAcc:'Already have an account?',
  // Dashboard
  welcomeBack:'Welcome back,', currentRank:'Current Rank',
  bestScore:'Best Score', streak:'Day Streak', percentile:'Percentile',
  upcomingExams:'Upcoming Exams', recentResults:'Recent Results',
  noExams:'No upcoming exams', startExam:'Start Exam',
  viewResult:'View Result', myPerf:'My Performance', achievements:'Achievements',
  // Exam
  examInstr:'Exam Instructions', startNow:'Start Exam Now',
  submitExam:'Submit Exam', timeLeft:'Time Remaining',
  answered:'Answered', unanswered:'Not Answered', flagged:'Marked for Review',
  notVisited:'Not Visited', question:'Question', saveNext:'Save & Next',
  markReview:'Mark for Review', clearResp:'Clear Response',
  confirmSub:'Confirm Submission',
  subWarn:'You have unanswered questions. Are you sure you want to submit?',
  // Result
  yourResult:'Your Result', score:'Score', allIndiaRank:'All India Rank',
  accuracy:'Accuracy', correct:'Correct', incorrect:'Incorrect', skipped:'Skipped',
  downloadPDF:'Download PDF', shareResult:'Share Result',
  viewAnalysis:'View Analysis', viewLeaderboard:'View Leaderboard',
  // Terms
  termsTitle:'Terms & Conditions', acceptAll:'I Accept All Terms',
  decline:'Decline', lastUpdated:'Last Updated: March 2026',
  // Admin
  adminDash:'Admin Dashboard', students:'Students', manageExams:'Manage Exams',
  questionBank:'Question Bank', liveMonitoring:'Live Monitoring',
  reports:'Reports', totalStudents:'Total Students', activeExams:'Active Exams',
  todayAttempts:"Today's Attempts", cheatAlerts:'Cheat Alerts',
  // Common
  loading2:'Loading...', error:'Error', save:'Save', cancel:'Cancel',
  back:'← Back', next:'Next →', search:'Search...', filter:'Filter',
  export:'Export', actions:'Actions', status:'Status', active:'Active',
  inactive:'Inactive', view:'View', edit:'Edit', delete:'Delete',
  submit:'Submit', goHome:'Go to Home', pageNotFound:'Page Not Found',
  strongTopics:'Strong Topics', weakTopics:'Weak Topics', reviseNow:'Revise Now',
  downloadAdmit:'Download Admit Card',
  footer:'NEET · NEET PG · JEE · CUET',
}

export const HI_TEXTS = {
  home:'होम', features:'सुविधाएं', results:'परिणाम', pricing:'मूल्य',
  login:'लॉगिन', logout:'लॉगआउट', register:'पंजीकरण', dashboard:'डैशबोर्ड',
  profile:'प्रोफाइल', exams:'परीक्षाएं', leaderboard:'लीडरबोर्ड',
  analytics:'विश्लेषण', certificate:'प्रमाण पत्र', settings:'सेटिंग्स',
  notifications:'सूचनाएं', admitCard:'प्रवेश पत्र',
  heroTitle:'भारत का सबसे उन्नत\nNEET परीक्षा मंच',
  heroSub:'वास्तविक रैंकिंग। वास्तविक परिणाम। प्रदर्शन या ईमानदारी में कोई समझौता नहीं।',
  startFree:'नि:शुल्क परीक्षा शुरू करें', viewDemo:'डेमो देखें',
  stat1v:'50,000+', stat1l:'छात्र',
  stat2v:'1,20,000+', stat2l:'परीक्षाएं दी गईं',
  stat3v:'99.9%', stat3l:'अपटाइम',
  stat4v:'#1', stat4l:'NEET मंच',
  featuresTitle:'NEET क्रैक करने के लिए सब कुछ',
  ctaLine:'आज अपनी NEET यात्रा शुरू करें।',
  regFree:'नि:शुल्क पंजीकरण करें →',
  loginTitle:'वापस आपका स्वागत है', loginSub:'अपने अकाउंट में लॉगिन करें',
  emailLabel:'ईमेल / रोल नंबर', emailPlaceholder:'student@proverank.com',
  passLabel:'पासवर्ड', passPlaceholder:'पासवर्ड दर्ज करें',
  forgot:'पासवर्ड भूल गए?', loginBtn:'लॉगिन करें →',
  loading:'लॉगिन हो रहा है...', noAcc:'अकाउंट नहीं है?',
  regTitle:'अपना खाता बनाएं', regSub:'आज ProveRank से जुड़ें',
  nameLabel:'पूरा नाम', phoneLabel:'मोबाइल नंबर',
  otpLabel:'OTP (6 अंक)', otpSent:'आपके नंबर पर OTP भेजा गया',
  regBtn:'खाता बनाएं →', haveAcc:'पहले से खाता है?',
  welcomeBack:'वापस आपका स्वागत है,', currentRank:'वर्तमान रैंक',
  bestScore:'सर्वश्रेष्ठ स्कोर', streak:'दिन की लकीर', percentile:'प्रतिशतक',
  upcomingExams:'आगामी परीक्षाएं', recentResults:'हाल के परिणाम',
  noExams:'कोई आगामी परीक्षा नहीं', startExam:'परीक्षा शुरू करें',
  viewResult:'परिणाम देखें', myPerf:'मेरा प्रदर्शन', achievements:'उपलब्धियां',
  examInstr:'परीक्षा निर्देश', startNow:'अभी परीक्षा शुरू करें',
  submitExam:'परीक्षा जमा करें', timeLeft:'शेष समय',
  answered:'उत्तर दिया', unanswered:'उत्तर नहीं दिया', flagged:'समीक्षा के लिए चिह्नित',
  notVisited:'नहीं देखा', question:'प्रश्न', saveNext:'सहेजें और आगे बढ़ें',
  markReview:'समीक्षा के लिए चिह्नित करें', clearResp:'उत्तर साफ करें',
  confirmSub:'जमा करने की पुष्टि',
  subWarn:'आपके पास अनुत्तरित प्रश्न हैं। क्या आप जमा करना चाहते हैं?',
  yourResult:'आपका परिणाम', score:'स्कोर', allIndiaRank:'अखिल भारत रैंक',
  accuracy:'सटीकता', correct:'सही', incorrect:'गलत', skipped:'छोड़े',
  downloadPDF:'PDF डाउनलोड करें', shareResult:'परिणाम साझा करें',
  viewAnalysis:'विश्लेषण देखें', viewLeaderboard:'लीडरबोर्ड देखें',
  termsTitle:'नियम और शर्तें', acceptAll:'मैं सभी शर्तें स्वीकार करता/करती हूं',
  decline:'अस्वीकार करें', lastUpdated:'अंतिम अपडेट: मार्च 2026',
  adminDash:'व्यवस्थापक डैशबोर्ड', students:'छात्र', manageExams:'परीक्षाएं प्रबंधित करें',
  questionBank:'प्रश्न बैंक', liveMonitoring:'लाइव निगरानी',
  reports:'रिपोर्ट', totalStudents:'कुल छात्र', activeExams:'सक्रिय परीक्षाएं',
  todayAttempts:'आज के प्रयास', cheatAlerts:'धोखाधड़ी अलर्ट',
  loading2:'लोड हो रहा है...', error:'त्रुटि', save:'सहेजें', cancel:'रद्द करें',
  back:'← वापस', next:'आगे →', search:'खोजें...', filter:'फ़िल्टर',
  export:'निर्यात', actions:'क्रियाएं', status:'स्थिति', active:'सक्रिय',
  inactive:'निष्क्रिय', view:'देखें', edit:'संपादित करें', delete:'हटाएं',
  submit:'जमा करें', goHome:'होम पर जाएं', pageNotFound:'पृष्ठ नहीं मिला',
  strongTopics:'मजबूत विषय', weakTopics:'कमजोर विषय', reviseNow:'अभी दोहराएं',
  downloadAdmit:'प्रवेश पत्र डाउनलोड करें',
  footer:'NEET · NEET PG · JEE · CUET',
}
